name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: |
          echo "Running ESLint..."
          npm run lint
          if [ $? -ne 0 ]; then
            echo "❌ ESLint found errors!"
            exit 1
          fi
          echo "✅ ESLint passed!"

  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run TypeScript check
        run: |
          echo "Running TypeScript check..."
          npm run typecheck
          if [ $? -ne 0 ]; then
            echo "❌ TypeScript check found errors!"
            exit 1
          fi
          echo "✅ TypeScript check passed!"

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: |
          echo "Building project..."
          npm run build
          if [ $? -ne 0 ]; then
            echo "❌ Build failed!"
            exit 1
          fi
          echo "✅ Build succeeded!"
        
      - name: Check build output
        run: |
          if [ -d ".output" ] || [ -d ".vercel" ]; then
            echo "✅ Build output found"
          else
            echo "❌ Build output directory not found"
            exit 1
          fi

  test:
    name: API Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run API tests
        run: |
          echo "Running API tests..."
          npm run test:data
          if [ $? -ne 0 ]; then
            echo "❌ API tests failed!"
            exit 1
          fi
          echo "✅ API tests passed!"

  # Summary job to require all checks to pass
  ci-status:
    name: CI Status
    runs-on: ubuntu-latest
    needs: [lint, typecheck, build, test]
    if: always()
    
    steps:
      - name: Check CI Status
        run: |
          if [ "${{ contains(needs.*.result, 'failure') }}" == "true" ]; then
            echo "❌ CI checks failed! Please fix the errors above."
            exit 1
          else
            echo "✅ All CI checks passed successfully!"
          fi